### ISSUE TITLE
Issues on biography.html

### ISSUE THREAD

**Issue by nkarampi** [anoulis/tsoum1#1]
-A problem with my footer.
-Don't use style on HTML file.
-Use body, header tags correctly. 
-Use lists to write the bio of every member
@anoulis

**Comment by anoulis** [comment]
@nkarampi i can't move the footer in bottom.
Only if we mention it as fixed.
And in generall i prepered it fixed.

**Comment by anoulis** [comment]
My friend @nkarampi i fixed overall.
But i have to say again that i prefer footer to be fixed.

**Comment by nkarampi** [comment]
Hello @anoulis 
Thanks for the instant reply.
I think the footers are always on the bottom of a webpage and not fixed. @tsik1 what do you think?
@anoulis Have a wonderful night!

**Comment by anoulis** [comment]
@nkarampi ok.
I agree then to let it as it is now.
Goodnight fellow

**Comment by anoulis** [comment]
I think that the issue can be closed.
Good job everyone.

**Comment by anoulis** [comment]
close #1

**Comment by anoulis** [comment]
Someone @nkarampi @tsik1 to fix the alt in biography images 
And in other html files if needed

**Comment by anoulis** [comment]
done
