### ISSUE TITLE
Someone to make News.html completely responsive

### ISSUE THREAD

**Issue by anoulis** [anoulis/tsoum1#4]
Well fellows @nkarampi and @tsik1 
Needed an image as a background.
It should be centered and in fullscreen mode.
Also the colour of headlines could be changed with a different than white.

**Comment by nkarampi** [comment]
Someone fill with more news! 
I will soon add a background and I think it's better with icons for the social.

**Comment by anoulis** [comment]
Come on @nkarampi @tsik1 
Somenone to do what the title says

**Comment by anoulis** [comment]
done
