### ISSUE TITLE
Warning Variable colorful text

### ISSUE THREAD

**Issue by anoulis** [anoulis/tsoum1#9]
Needed someone to add color in text.
Green for correct,red for wrong,yellow for the rest warnings.
@nkarampi @tsik1

**Comment by nkarampi** [comment]
color on correct/wrong?

**Comment by anoulis** [comment]
Green color when answer is correct for text "Correct"
Red color when answer is wrong for text "Wrong"
Yellow when we display the rest warnings

**Comment by nkarampi** [comment]
No need..
